services:

  postgres:
    image: postgres:16
    container_name: nyc-airflow-postgres

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 10


  airflow-init:
    image: apache/airflow:3.1.0
    container_name: nyc-airflow-init

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      # Airflow 3 Simple Auth Manager
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: "admin:admin"

    command:
      - bash
      - -c
      - |
        airflow db migrate

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins


  airflow-webserver:
    image: apache/airflow:3.1.0
    container_name: nyc-airflow-webserver

    depends_on:
      airflow-init:
        condition: service_completed_successfully

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      # Airflow 3 Simple Auth Manager
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: "admin:admin"

    command:
      - api-server

    ports:
      - "8080:8080"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins


  airflow-scheduler:
    image: apache/airflow:3.1.0
    container_name: nyc-airflow-scheduler

    depends_on:
      airflow-init:
        condition: service_completed_successfully

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      # Airflow 3 Simple Auth Manager
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: "admin:admin"

    command:
      - scheduler

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins


volumes:
  airflow_postgres_data: